name: grant-tag
run-name: grant-tag
on:
  push:
    branches:
      - master
    paths:
      - solrust/Cargo.toml
      - solrust_derive/Cargo.toml
      - solrust_derive_internals/Cargo.toml
env:
  CARGO_TERM_COLOR: always
  TZ: "Asia/Tokyo"
jobs:
  grant-tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: detect-solrust-version
        with:
          create-tag: false
          version-command: cargo read-manifest --manifest-path=solrust/Cargo.toml | jq -r .version
      - uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{steps.detect-solrust-version.outputs.current-version}}
          tag_prefix: "solrust_v"
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: salsify/action-detect-and-tag-new-version@v2
        id: detect-solrust-derive-version
        with:
          create-tag: false
          version-command: cargo read-manifest --manifest-path=solrust_derive/Cargo.toml | jq -r .version
      - uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{steps.detect-solrust-derive-version.outputs.current-version}}
          tag_prefix: "solrust_derive_v"
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: salsify/action-detect-and-tag-new-version@v2
        id: detect-solrust-derive-internals-version
        with:
          create-tag: false
          version-command: cargo read-manifest --manifest-path=solrust_derive_internals/Cargo.toml | jq -r .version
      - uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{steps.detect-solrust-derive-internals-version.outputs.current-version}}
          tag_prefix: "solrust_derive_internals_v"
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
