name: run-tests
run-name: run-tests
on:
  pull_request:
    branches:
      - master
      - develop
env:
  CARGO_TERM_COLOR: always
jobs:
  run-all-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: cargo test
