name: run-tests
run-name: run-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always
  TZ: "Asia/Tokyo"
jobs:
  run-all-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: docker run --rm -d -p 8983:8983 solr:9.1.0 solr-precreate example
      - run: cargo test -- --include-ignored
